# Generated by Django 4.1.6 on 2023-05-21 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_tasklabel_task_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklabel',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
