# Generated by Django 4.1.6 on 2023-04-17 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='status',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
